services:
  db-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: pedidos_veloz
    ports:
      - "5432:5432"
    networks:
      - veloz-network

  orders-service:
    build: ./services/orders
    environment:
      - DB_HOST=db-postgres
    depends_on:
      - db-postgres
    networks:
      - veloz-network

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:80"
    depends_on:
      - orders-service
    networks:
      - veloz-network

networks:
  veloz-network:
    driver: bridge
