events {
    worker_connections 1024;
}
http {
    upstream orders {
        server orders-service:3000;
    }
    server {
        listen 80;
        location /api/orders/ {
            proxy_pass http://orders;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
